language: ruby
rvm: 2.5.1
services:
  - postgresql
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.3
  - sudo apt-get install -qq libpq-dev
before_script:
  - psql -c 'create database microlearn_test;' -U postgres
  - bundle
script:
  - bundle exec rspec
