ruby '2.5.1'

source 'https://rubygems.org'

gem 'sinatra'
gem 'sqlite3'
gem 'datamapper'
gem 'dm-sqlite-adapter'
gem 'rerun'
gem 'json'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'dm-noisy-failures'
gem 'gon-sinatra'
gem 'rufus-scheduler'
gem 'http'
