# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    pre:
      - sudo apt-get install postgresql-9.4 postgresql-server-dev-9.4 libpq-dev
      # Start Postgres 9.6.
      - sudo service postgresql start 9.4
      # Create a new test database.
      - sudo -u postgres psql -p 5432 -c "create database microlearn_test;"
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.1
        environment:
            PGUSER: root

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_DB: microlearn_test
          POSTGRES_USER: root

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3

      - run:
          name: run tests
          command: |
            bundle exec rspec
      - run:
          name: collect coverage
          command: |
            cat ./coverage/.last_run.json | coveralls
